//# Do not modify this file -- YOUR CHANGES WILL BE ERASED!
//  Generated by SAP Cloud Platform Android SDK 2.0.0, on Fri Mar 15 17:00:06 BRT 2019
//  Proxy Generator Version: 18.11.0-9ee469-20181119

package com.example.sapinitialproject.ESPM.internal;

public abstract class ESPMContainerFactory {
    public static void registerAll() {
        com.example.sapinitialproject.ESPM.ESPMContainerMetadata.ComplexTypes.address.registerFactory(new com.example.sapinitialproject.ESPM.internal.ESPMContainerFactory.CreateAddress());
        com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.customer.registerFactory(new com.example.sapinitialproject.ESPM.internal.ESPMContainerFactory.CreateCustomer());
        com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.product.registerFactory(new com.example.sapinitialproject.ESPM.internal.ESPMContainerFactory.CreateProduct());
        com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.productCategory.registerFactory(new com.example.sapinitialproject.ESPM.internal.ESPMContainerFactory.CreateProductCategory());
        com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.productText.registerFactory(new com.example.sapinitialproject.ESPM.internal.ESPMContainerFactory.CreateProductText());
        com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.purchaseOrderHeader.registerFactory(new com.example.sapinitialproject.ESPM.internal.ESPMContainerFactory.CreatePurchaseOrderHeader());
        com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.purchaseOrderItem.registerFactory(new com.example.sapinitialproject.ESPM.internal.ESPMContainerFactory.CreatePurchaseOrderItem());
        com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.salesOrderHeader.registerFactory(new com.example.sapinitialproject.ESPM.internal.ESPMContainerFactory.CreateSalesOrderHeader());
        com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.salesOrderItem.registerFactory(new com.example.sapinitialproject.ESPM.internal.ESPMContainerFactory.CreateSalesOrderItem());
        com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.stock.registerFactory(new com.example.sapinitialproject.ESPM.internal.ESPMContainerFactory.CreateStock());
        com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.supplier.registerFactory(new com.example.sapinitialproject.ESPM.internal.ESPMContainerFactory.CreateSupplier());
        com.example.sapinitialproject.ESPM.internal.ESPMContainerStaticResolver.resolve();
    }

    public static class CreateAddress
    extends com.sap.cloud.mobile.odata.core.ObjectFactory {
        /**
         ** {@inheritDoc}
         **/
        @java.lang.Override public @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull Object create() {
            return new com.example.sapinitialproject.ESPM.Address(false);
        }
    }

    public static class CreateCustomer
    extends com.sap.cloud.mobile.odata.core.ObjectFactory {
        /**
         ** {@inheritDoc}
         **/
        @java.lang.Override public @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull Object create() {
            return new com.example.sapinitialproject.ESPM.Customer(false);
        }
    }

    public static class CreateProduct
    extends com.sap.cloud.mobile.odata.core.ObjectFactory {
        /**
         ** {@inheritDoc}
         **/
        @java.lang.Override public @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull Object create() {
            return new com.example.sapinitialproject.ESPM.Product(false);
        }
    }

    public static class CreateProductCategory
    extends com.sap.cloud.mobile.odata.core.ObjectFactory {
        /**
         ** {@inheritDoc}
         **/
        @java.lang.Override public @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull Object create() {
            return new com.example.sapinitialproject.ESPM.ProductCategory(false);
        }
    }

    public static class CreateProductText
    extends com.sap.cloud.mobile.odata.core.ObjectFactory {
        /**
         ** {@inheritDoc}
         **/
        @java.lang.Override public @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull Object create() {
            return new com.example.sapinitialproject.ESPM.ProductText(false);
        }
    }

    public static class CreatePurchaseOrderHeader
    extends com.sap.cloud.mobile.odata.core.ObjectFactory {
        /**
         ** {@inheritDoc}
         **/
        @java.lang.Override public @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull Object create() {
            return new com.example.sapinitialproject.ESPM.PurchaseOrderHeader(false);
        }
    }

    public static class CreatePurchaseOrderItem
    extends com.sap.cloud.mobile.odata.core.ObjectFactory {
        /**
         ** {@inheritDoc}
         **/
        @java.lang.Override public @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull Object create() {
            return new com.example.sapinitialproject.ESPM.PurchaseOrderItem(false);
        }
    }

    public static class CreateSalesOrderHeader
    extends com.sap.cloud.mobile.odata.core.ObjectFactory {
        /**
         ** {@inheritDoc}
         **/
        @java.lang.Override public @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull Object create() {
            return new com.example.sapinitialproject.ESPM.SalesOrderHeader(false);
        }
    }

    public static class CreateSalesOrderItem
    extends com.sap.cloud.mobile.odata.core.ObjectFactory {
        /**
         ** {@inheritDoc}
         **/
        @java.lang.Override public @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull Object create() {
            return new com.example.sapinitialproject.ESPM.SalesOrderItem(false);
        }
    }

    public static class CreateStock
    extends com.sap.cloud.mobile.odata.core.ObjectFactory {
        /**
         ** {@inheritDoc}
         **/
        @java.lang.Override public @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull Object create() {
            return new com.example.sapinitialproject.ESPM.Stock(false);
        }
    }

    public static class CreateSupplier
    extends com.sap.cloud.mobile.odata.core.ObjectFactory {
        /**
         ** {@inheritDoc}
         **/
        @java.lang.Override public @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull Object create() {
            return new com.example.sapinitialproject.ESPM.Supplier(false);
        }
    }
}
