//# Do not modify this file -- YOUR CHANGES WILL BE ERASED!
//  Generated by SAP Cloud Platform Android SDK 2.0.0, on Fri Mar 15 17:00:06 BRT 2019
//  Proxy Generator Version: 18.11.0-9ee469-20181119

package com.example.sapinitialproject.ESPM;

public abstract class ESPMContainerMetadata {
    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.csdl.CsdlDocument document = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.resolve();

    private static @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.csdl.CsdlDocument resolve() {
        com.example.sapinitialproject.ESPM.internal.ESPMContainerFactory.registerAll();
        com.example.sapinitialproject.ESPM.internal.ESPMContainerMetadataParser.parsed.setGeneratedProxies(true);
        com.example.sapinitialproject.ESPM.internal.ESPMContainerMetadataParser.parsed.setOpenEnumerations(true);
        return com.example.sapinitialproject.ESPM.internal.ESPMContainerMetadataParser.parsed;
    }

    public abstract static class ComplexTypes {
        public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.ComplexType address = com.example.sapinitialproject.ESPM.internal.ESPMContainerMetadataParser.parsed.getComplexType("ESPM.Address");
    }

    public abstract static class EntityTypes {
        public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.EntityType customer = com.example.sapinitialproject.ESPM.internal.ESPMContainerMetadataParser.parsed.getEntityType("ESPM.Customer");

        public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.EntityType product = com.example.sapinitialproject.ESPM.internal.ESPMContainerMetadataParser.parsed.getEntityType("ESPM.Product");

        public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.EntityType productCategory = com.example.sapinitialproject.ESPM.internal.ESPMContainerMetadataParser.parsed.getEntityType("ESPM.ProductCategory");

        public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.EntityType productText = com.example.sapinitialproject.ESPM.internal.ESPMContainerMetadataParser.parsed.getEntityType("ESPM.ProductText");

        public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.EntityType purchaseOrderHeader = com.example.sapinitialproject.ESPM.internal.ESPMContainerMetadataParser.parsed.getEntityType("ESPM.PurchaseOrderHeader");

        public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.EntityType purchaseOrderItem = com.example.sapinitialproject.ESPM.internal.ESPMContainerMetadataParser.parsed.getEntityType("ESPM.PurchaseOrderItem");

        public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.EntityType salesOrderHeader = com.example.sapinitialproject.ESPM.internal.ESPMContainerMetadataParser.parsed.getEntityType("ESPM.SalesOrderHeader");

        public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.EntityType salesOrderItem = com.example.sapinitialproject.ESPM.internal.ESPMContainerMetadataParser.parsed.getEntityType("ESPM.SalesOrderItem");

        public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.EntityType stock = com.example.sapinitialproject.ESPM.internal.ESPMContainerMetadataParser.parsed.getEntityType("ESPM.Stock");

        public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.EntityType supplier = com.example.sapinitialproject.ESPM.internal.ESPMContainerMetadataParser.parsed.getEntityType("ESPM.Supplier");
    }

    public abstract static class EntitySets {
        public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.EntitySet customers = com.example.sapinitialproject.ESPM.internal.ESPMContainerMetadataParser.parsed.getEntitySet("Customers");

        public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.EntitySet productCategories = com.example.sapinitialproject.ESPM.internal.ESPMContainerMetadataParser.parsed.getEntitySet("ProductCategories");

        public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.EntitySet productTexts = com.example.sapinitialproject.ESPM.internal.ESPMContainerMetadataParser.parsed.getEntitySet("ProductTexts");

        public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.EntitySet products = com.example.sapinitialproject.ESPM.internal.ESPMContainerMetadataParser.parsed.getEntitySet("Products");

        public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.EntitySet purchaseOrderHeaders = com.example.sapinitialproject.ESPM.internal.ESPMContainerMetadataParser.parsed.getEntitySet("PurchaseOrderHeaders");

        public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.EntitySet purchaseOrderItems = com.example.sapinitialproject.ESPM.internal.ESPMContainerMetadataParser.parsed.getEntitySet("PurchaseOrderItems");

        public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.EntitySet salesOrderHeaders = com.example.sapinitialproject.ESPM.internal.ESPMContainerMetadataParser.parsed.getEntitySet("SalesOrderHeaders");

        public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.EntitySet salesOrderItems = com.example.sapinitialproject.ESPM.internal.ESPMContainerMetadataParser.parsed.getEntitySet("SalesOrderItems");

        public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.EntitySet stock = com.example.sapinitialproject.ESPM.internal.ESPMContainerMetadataParser.parsed.getEntitySet("Stock");

        public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.EntitySet suppliers = com.example.sapinitialproject.ESPM.internal.ESPMContainerMetadataParser.parsed.getEntitySet("Suppliers");
    }

    public abstract static class ActionImports {
        public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.DataMethod generateSamplePurchaseOrders = com.example.sapinitialproject.ESPM.internal.ESPMContainerMetadataParser.parsed.getDataMethod("GenerateSamplePurchaseOrders");

        public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.DataMethod generateSampleSalesOrders = com.example.sapinitialproject.ESPM.internal.ESPMContainerMetadataParser.parsed.getDataMethod("GenerateSampleSalesOrders");

        public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.DataMethod resetSampleData = com.example.sapinitialproject.ESPM.internal.ESPMContainerMetadataParser.parsed.getDataMethod("ResetSampleData");

        public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.DataMethod updateSalesOrderStatus = com.example.sapinitialproject.ESPM.internal.ESPMContainerMetadataParser.parsed.getDataMethod("UpdateSalesOrderStatus");
    }
}
