//# Do not modify this file -- YOUR CHANGES WILL BE ERASED!
//  Generated by SAP Cloud Platform Android SDK 2.0.0, on Fri Mar 15 17:00:06 BRT 2019
//  Proxy Generator Version: 18.11.0-9ee469-20181119

package com.example.sapinitialproject.ESPM;

public class ProductCategory extends com.sap.cloud.mobile.odata.EntityValue implements android.os.Parcelable {
    public static final android.os.Parcelable.Creator<ProductCategory> CREATOR = new android.os.Parcelable.Creator<ProductCategory>() {
        public ProductCategory createFromParcel(android.os.Parcel in) {
            com.sap.cloud.mobile.odata.JsonEntityProvider provider = com.sap.cloud.mobile.odata.JsonEntityProvider.withMetadata(ESPMContainerMetadata.document);
            ESPMContainer service = new ESPMContainer(provider);
            com.sap.cloud.mobile.odata.DataQuery query = com.sap.cloud.mobile.odata.FromJSON.entity(in.readString());
            query.setEntitySet(ESPMContainerMetadata.EntitySets.productCategories);
            query.setEntityType(ESPMContainerMetadata.EntityTypes.productCategory);
            com.sap.cloud.mobile.odata.EntityValue entity = service.executeQuery(query).getRequiredEntity();
            return (ProductCategory)entity;
        }

        public ProductCategory[] newArray(int size) {
            return new ProductCategory[size];
        }
    };

    public int describeContents() {
        return 0;
    }

    public void writeToParcel(android.os.Parcel out, int flags) {
        out.writeString(com.sap.cloud.mobile.odata.ToJSON.entity(this, com.sap.cloud.mobile.odata.DataContext.FULL_METADATA));
    }

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property category = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.productCategory.getProperty("Category");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property categoryName = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.productCategory.getProperty("CategoryName");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property mainCategory = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.productCategory.getProperty("MainCategory");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property mainCategoryName = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.productCategory.getProperty("MainCategoryName");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property numberOfProducts = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.productCategory.getProperty("NumberOfProducts");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property updatedTimestamp = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.productCategory.getProperty("UpdatedTimestamp");

    /**
     ** See <a href='#ProductCategory-boolean-'>ProductCategory(boolean)</a>.
     **/
    public ProductCategory() {
        this(true);
    }

    public ProductCategory(final boolean withDefaults) {
        super(withDefaults, com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.productCategory);
    }

    public @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.example.sapinitialproject.ESPM.ProductCategory copy() {
        return com.example.sapinitialproject.ESPM.internal.Any_as_com_example_sapinitialproject_ESPM_ProductCategory.cast(this.copyEntity());
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String getCategory() {
        return com.sap.cloud.mobile.odata.StringValue.toNullable(this.getOptionalValue(com.example.sapinitialproject.ESPM.ProductCategory.category));
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String getCategoryName() {
        return com.sap.cloud.mobile.odata.StringValue.toNullable(this.getOptionalValue(com.example.sapinitialproject.ESPM.ProductCategory.categoryName));
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String getMainCategory() {
        return com.sap.cloud.mobile.odata.StringValue.toNullable(this.getOptionalValue(com.example.sapinitialproject.ESPM.ProductCategory.mainCategory));
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String getMainCategoryName() {
        return com.sap.cloud.mobile.odata.StringValue.toNullable(this.getOptionalValue(com.example.sapinitialproject.ESPM.ProductCategory.mainCategoryName));
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable Long getNumberOfProducts() {
        return com.sap.cloud.mobile.odata.LongValue.toNullable(this.getOptionalValue(com.example.sapinitialproject.ESPM.ProductCategory.numberOfProducts));
    }

    public @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.example.sapinitialproject.ESPM.ProductCategory getOld() {
        return com.example.sapinitialproject.ESPM.internal.Any_as_com_example_sapinitialproject_ESPM_ProductCategory.cast(this.getOldEntity());
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable com.sap.cloud.mobile.odata.LocalDateTime getUpdatedTimestamp() {
        return com.sap.cloud.mobile.odata.LocalDateTime.castOptional(this.getOptionalValue(com.example.sapinitialproject.ESPM.ProductCategory.updatedTimestamp));
    }

    /**
     ** {@inheritDoc}
     **/
    @java.lang.Override public boolean isProxy() {
        return true;
    }

    public static @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.EntityKey key(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String category) {
        return new com.sap.cloud.mobile.odata.EntityKey().with("Category", com.sap.cloud.mobile.odata.StringValue.ofNullable(category));
    }

    public static @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull java.util.List<com.example.sapinitialproject.ESPM.@org.jetbrains.annotations.NotNull ProductCategory> list(final @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.EntityValueList from) {
        return com.sap.cloud.mobile.odata.core.ListConverter.<com.sap.cloud.mobile.odata.EntityValue,com.example.sapinitialproject.ESPM.ProductCategory>convert(from.toGeneric());
    }

    public void setCategory(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String value) {
        this.setOptionalValue(com.example.sapinitialproject.ESPM.ProductCategory.category, com.sap.cloud.mobile.odata.StringValue.ofNullable(value));
    }

    public void setCategoryName(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String value) {
        this.setOptionalValue(com.example.sapinitialproject.ESPM.ProductCategory.categoryName, com.sap.cloud.mobile.odata.StringValue.ofNullable(value));
    }

    public void setMainCategory(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String value) {
        this.setOptionalValue(com.example.sapinitialproject.ESPM.ProductCategory.mainCategory, com.sap.cloud.mobile.odata.StringValue.ofNullable(value));
    }

    public void setMainCategoryName(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String value) {
        this.setOptionalValue(com.example.sapinitialproject.ESPM.ProductCategory.mainCategoryName, com.sap.cloud.mobile.odata.StringValue.ofNullable(value));
    }

    public void setNumberOfProducts(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable Long value) {
        this.setOptionalValue(com.example.sapinitialproject.ESPM.ProductCategory.numberOfProducts, com.sap.cloud.mobile.odata.LongValue.ofNullable(value));
    }

    public void setUpdatedTimestamp(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable com.sap.cloud.mobile.odata.LocalDateTime value) {
        this.setOptionalValue(com.example.sapinitialproject.ESPM.ProductCategory.updatedTimestamp, value);
    }
}
