//# Do not modify this file -- YOUR CHANGES WILL BE ERASED!
//  Generated by SAP Cloud Platform Android SDK 2.0.0, on Fri Mar 15 17:00:06 BRT 2019
//  Proxy Generator Version: 18.11.0-9ee469-20181119

package com.example.sapinitialproject.ESPM;

public class Product extends com.sap.cloud.mobile.odata.EntityValue implements android.os.Parcelable {
    public static final android.os.Parcelable.Creator<Product> CREATOR = new android.os.Parcelable.Creator<Product>() {
        public Product createFromParcel(android.os.Parcel in) {
            com.sap.cloud.mobile.odata.JsonEntityProvider provider = com.sap.cloud.mobile.odata.JsonEntityProvider.withMetadata(ESPMContainerMetadata.document);
            ESPMContainer service = new ESPMContainer(provider);
            com.sap.cloud.mobile.odata.DataQuery query = com.sap.cloud.mobile.odata.FromJSON.entity(in.readString());
            query.setEntitySet(ESPMContainerMetadata.EntitySets.products);
            query.setEntityType(ESPMContainerMetadata.EntityTypes.product);
            com.sap.cloud.mobile.odata.EntityValue entity = service.executeQuery(query).getRequiredEntity();
            return (Product)entity;
        }

        public Product[] newArray(int size) {
            return new Product[size];
        }
    };

    public int describeContents() {
        return 0;
    }

    public void writeToParcel(android.os.Parcel out, int flags) {
        out.writeString(com.sap.cloud.mobile.odata.ToJSON.entity(this, com.sap.cloud.mobile.odata.DataContext.FULL_METADATA));
    }

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property category = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.product.getProperty("Category");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property categoryName = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.product.getProperty("CategoryName");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property currencyCode = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.product.getProperty("CurrencyCode");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property dimensionDepth = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.product.getProperty("DimensionDepth");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property dimensionHeight = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.product.getProperty("DimensionHeight");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property dimensionUnit = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.product.getProperty("DimensionUnit");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property dimensionWidth = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.product.getProperty("DimensionWidth");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property longDescription = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.product.getProperty("LongDescription");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property name = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.product.getProperty("Name");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property pictureUrl = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.product.getProperty("PictureUrl");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property price = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.product.getProperty("Price");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property productID = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.product.getProperty("ProductId");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property quantityUnit = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.product.getProperty("QuantityUnit");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property shortDescription = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.product.getProperty("ShortDescription");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property supplierID = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.product.getProperty("SupplierId");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property updatedTimestamp = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.product.getProperty("UpdatedTimestamp");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property weight = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.product.getProperty("Weight");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property weightUnit = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.product.getProperty("WeightUnit");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property stockDetails = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.product.getProperty("StockDetails");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property supplierDetails = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.product.getProperty("SupplierDetails");

    /**
     ** See <a href='#Product-boolean-'>Product(boolean)</a>.
     **/
    public Product() {
        this(true);
    }

    public Product(final boolean withDefaults) {
        super(withDefaults, com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.product);
    }

    public @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.example.sapinitialproject.ESPM.Product copy() {
        return com.example.sapinitialproject.ESPM.internal.Any_as_com_example_sapinitialproject_ESPM_Product.cast(this.copyEntity());
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String getCategory() {
        return com.sap.cloud.mobile.odata.StringValue.toNullable(this.getOptionalValue(com.example.sapinitialproject.ESPM.Product.category));
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String getCategoryName() {
        return com.sap.cloud.mobile.odata.StringValue.toNullable(this.getOptionalValue(com.example.sapinitialproject.ESPM.Product.categoryName));
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String getCurrencyCode() {
        return com.sap.cloud.mobile.odata.StringValue.toNullable(this.getOptionalValue(com.example.sapinitialproject.ESPM.Product.currencyCode));
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable java.math.BigDecimal getDimensionDepth() {
        return com.sap.cloud.mobile.odata.DecimalValue.toNullable(this.getOptionalValue(com.example.sapinitialproject.ESPM.Product.dimensionDepth));
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable java.math.BigDecimal getDimensionHeight() {
        return com.sap.cloud.mobile.odata.DecimalValue.toNullable(this.getOptionalValue(com.example.sapinitialproject.ESPM.Product.dimensionHeight));
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String getDimensionUnit() {
        return com.sap.cloud.mobile.odata.StringValue.toNullable(this.getOptionalValue(com.example.sapinitialproject.ESPM.Product.dimensionUnit));
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable java.math.BigDecimal getDimensionWidth() {
        return com.sap.cloud.mobile.odata.DecimalValue.toNullable(this.getOptionalValue(com.example.sapinitialproject.ESPM.Product.dimensionWidth));
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String getLongDescription() {
        return com.sap.cloud.mobile.odata.StringValue.toNullable(this.getOptionalValue(com.example.sapinitialproject.ESPM.Product.longDescription));
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String getName() {
        return com.sap.cloud.mobile.odata.StringValue.toNullable(this.getOptionalValue(com.example.sapinitialproject.ESPM.Product.name));
    }

    public @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.example.sapinitialproject.ESPM.Product getOld() {
        return com.example.sapinitialproject.ESPM.internal.Any_as_com_example_sapinitialproject_ESPM_Product.cast(this.getOldEntity());
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String getPictureUrl() {
        return com.sap.cloud.mobile.odata.StringValue.toNullable(this.getOptionalValue(com.example.sapinitialproject.ESPM.Product.pictureUrl));
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable java.math.BigDecimal getPrice() {
        return com.sap.cloud.mobile.odata.DecimalValue.toNullable(this.getOptionalValue(com.example.sapinitialproject.ESPM.Product.price));
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String getProductID() {
        return com.sap.cloud.mobile.odata.StringValue.toNullable(this.getOptionalValue(com.example.sapinitialproject.ESPM.Product.productID));
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String getQuantityUnit() {
        return com.sap.cloud.mobile.odata.StringValue.toNullable(this.getOptionalValue(com.example.sapinitialproject.ESPM.Product.quantityUnit));
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String getShortDescription() {
        return com.sap.cloud.mobile.odata.StringValue.toNullable(this.getOptionalValue(com.example.sapinitialproject.ESPM.Product.shortDescription));
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable com.example.sapinitialproject.ESPM.Stock getStockDetails() {
        return com.example.sapinitialproject.ESPM.internal.Any_asNullable_com_example_sapinitialproject_ESPM_Stock.cast(this.getOptionalValue(com.example.sapinitialproject.ESPM.Product.stockDetails));
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable com.example.sapinitialproject.ESPM.Supplier getSupplierDetails() {
        return com.example.sapinitialproject.ESPM.internal.Any_asNullable_com_example_sapinitialproject_ESPM_Supplier.cast(this.getOptionalValue(com.example.sapinitialproject.ESPM.Product.supplierDetails));
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String getSupplierID() {
        return com.sap.cloud.mobile.odata.StringValue.toNullable(this.getOptionalValue(com.example.sapinitialproject.ESPM.Product.supplierID));
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable com.sap.cloud.mobile.odata.LocalDateTime getUpdatedTimestamp() {
        return com.sap.cloud.mobile.odata.LocalDateTime.castOptional(this.getOptionalValue(com.example.sapinitialproject.ESPM.Product.updatedTimestamp));
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable java.math.BigDecimal getWeight() {
        return com.sap.cloud.mobile.odata.DecimalValue.toNullable(this.getOptionalValue(com.example.sapinitialproject.ESPM.Product.weight));
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String getWeightUnit() {
        return com.sap.cloud.mobile.odata.StringValue.toNullable(this.getOptionalValue(com.example.sapinitialproject.ESPM.Product.weightUnit));
    }

    /**
     ** {@inheritDoc}
     **/
    @java.lang.Override public boolean isProxy() {
        return true;
    }

    public static @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.EntityKey key(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String productID) {
        return new com.sap.cloud.mobile.odata.EntityKey().with("ProductId", com.sap.cloud.mobile.odata.StringValue.ofNullable(productID));
    }

    public static @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull java.util.List<com.example.sapinitialproject.ESPM.@org.jetbrains.annotations.NotNull Product> list(final @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.EntityValueList from) {
        return com.sap.cloud.mobile.odata.core.ListConverter.<com.sap.cloud.mobile.odata.EntityValue,com.example.sapinitialproject.ESPM.Product>convert(from.toGeneric());
    }

    public void setCategory(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String value) {
        this.setOptionalValue(com.example.sapinitialproject.ESPM.Product.category, com.sap.cloud.mobile.odata.StringValue.ofNullable(value));
    }

    public void setCategoryName(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String value) {
        this.setOptionalValue(com.example.sapinitialproject.ESPM.Product.categoryName, com.sap.cloud.mobile.odata.StringValue.ofNullable(value));
    }

    public void setCurrencyCode(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String value) {
        this.setOptionalValue(com.example.sapinitialproject.ESPM.Product.currencyCode, com.sap.cloud.mobile.odata.StringValue.ofNullable(value));
    }

    public void setDimensionDepth(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable java.math.BigDecimal value) {
        this.setOptionalValue(com.example.sapinitialproject.ESPM.Product.dimensionDepth, com.sap.cloud.mobile.odata.DecimalValue.ofNullable(value));
    }

    public void setDimensionHeight(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable java.math.BigDecimal value) {
        this.setOptionalValue(com.example.sapinitialproject.ESPM.Product.dimensionHeight, com.sap.cloud.mobile.odata.DecimalValue.ofNullable(value));
    }

    public void setDimensionUnit(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String value) {
        this.setOptionalValue(com.example.sapinitialproject.ESPM.Product.dimensionUnit, com.sap.cloud.mobile.odata.StringValue.ofNullable(value));
    }

    public void setDimensionWidth(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable java.math.BigDecimal value) {
        this.setOptionalValue(com.example.sapinitialproject.ESPM.Product.dimensionWidth, com.sap.cloud.mobile.odata.DecimalValue.ofNullable(value));
    }

    public void setLongDescription(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String value) {
        this.setOptionalValue(com.example.sapinitialproject.ESPM.Product.longDescription, com.sap.cloud.mobile.odata.StringValue.ofNullable(value));
    }

    public void setName(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String value) {
        this.setOptionalValue(com.example.sapinitialproject.ESPM.Product.name, com.sap.cloud.mobile.odata.StringValue.ofNullable(value));
    }

    public void setPictureUrl(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String value) {
        this.setOptionalValue(com.example.sapinitialproject.ESPM.Product.pictureUrl, com.sap.cloud.mobile.odata.StringValue.ofNullable(value));
    }

    public void setPrice(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable java.math.BigDecimal value) {
        this.setOptionalValue(com.example.sapinitialproject.ESPM.Product.price, com.sap.cloud.mobile.odata.DecimalValue.ofNullable(value));
    }

    public void setProductID(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String value) {
        this.setOptionalValue(com.example.sapinitialproject.ESPM.Product.productID, com.sap.cloud.mobile.odata.StringValue.ofNullable(value));
    }

    public void setQuantityUnit(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String value) {
        this.setOptionalValue(com.example.sapinitialproject.ESPM.Product.quantityUnit, com.sap.cloud.mobile.odata.StringValue.ofNullable(value));
    }

    public void setShortDescription(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String value) {
        this.setOptionalValue(com.example.sapinitialproject.ESPM.Product.shortDescription, com.sap.cloud.mobile.odata.StringValue.ofNullable(value));
    }

    public void setStockDetails(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable com.example.sapinitialproject.ESPM.Stock value) {
        this.setOptionalValue(com.example.sapinitialproject.ESPM.Product.stockDetails, value);
    }

    public void setSupplierDetails(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable com.example.sapinitialproject.ESPM.Supplier value) {
        this.setOptionalValue(com.example.sapinitialproject.ESPM.Product.supplierDetails, value);
    }

    public void setSupplierID(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String value) {
        this.setOptionalValue(com.example.sapinitialproject.ESPM.Product.supplierID, com.sap.cloud.mobile.odata.StringValue.ofNullable(value));
    }

    public void setUpdatedTimestamp(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable com.sap.cloud.mobile.odata.LocalDateTime value) {
        this.setOptionalValue(com.example.sapinitialproject.ESPM.Product.updatedTimestamp, value);
    }

    public void setWeight(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable java.math.BigDecimal value) {
        this.setOptionalValue(com.example.sapinitialproject.ESPM.Product.weight, com.sap.cloud.mobile.odata.DecimalValue.ofNullable(value));
    }

    public void setWeightUnit(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String value) {
        this.setOptionalValue(com.example.sapinitialproject.ESPM.Product.weightUnit, com.sap.cloud.mobile.odata.StringValue.ofNullable(value));
    }
}
