//# Do not modify this file -- YOUR CHANGES WILL BE ERASED!
//  Generated by SAP Cloud Platform Android SDK 2.0.0, on Fri Mar 15 17:00:06 BRT 2019
//  Proxy Generator Version: 18.11.0-9ee469-20181119

package com.example.sapinitialproject.ESPM;

public class SalesOrderItem extends com.sap.cloud.mobile.odata.EntityValue implements android.os.Parcelable {
    public static final android.os.Parcelable.Creator<SalesOrderItem> CREATOR = new android.os.Parcelable.Creator<SalesOrderItem>() {
        public SalesOrderItem createFromParcel(android.os.Parcel in) {
            com.sap.cloud.mobile.odata.JsonEntityProvider provider = com.sap.cloud.mobile.odata.JsonEntityProvider.withMetadata(ESPMContainerMetadata.document);
            ESPMContainer service = new ESPMContainer(provider);
            com.sap.cloud.mobile.odata.DataQuery query = com.sap.cloud.mobile.odata.FromJSON.entity(in.readString());
            query.setEntitySet(ESPMContainerMetadata.EntitySets.salesOrderItems);
            query.setEntityType(ESPMContainerMetadata.EntityTypes.salesOrderItem);
            com.sap.cloud.mobile.odata.EntityValue entity = service.executeQuery(query).getRequiredEntity();
            return (SalesOrderItem)entity;
        }

        public SalesOrderItem[] newArray(int size) {
            return new SalesOrderItem[size];
        }
    };

    public int describeContents() {
        return 0;
    }

    public void writeToParcel(android.os.Parcel out, int flags) {
        out.writeString(com.sap.cloud.mobile.odata.ToJSON.entity(this, com.sap.cloud.mobile.odata.DataContext.FULL_METADATA));
    }

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property currencyCode = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.salesOrderItem.getProperty("CurrencyCode");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property deliveryDate = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.salesOrderItem.getProperty("DeliveryDate");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property grossAmount = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.salesOrderItem.getProperty("GrossAmount");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property itemNumber = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.salesOrderItem.getProperty("ItemNumber");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property netAmount = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.salesOrderItem.getProperty("NetAmount");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property productID = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.salesOrderItem.getProperty("ProductId");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property quantity = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.salesOrderItem.getProperty("Quantity");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property quantityUnit = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.salesOrderItem.getProperty("QuantityUnit");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property salesOrderID = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.salesOrderItem.getProperty("SalesOrderId");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property taxAmount = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.salesOrderItem.getProperty("TaxAmount");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property header = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.salesOrderItem.getProperty("Header");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property productDetails = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.salesOrderItem.getProperty("ProductDetails");

    /**
     ** See <a href='#SalesOrderItem-boolean-'>SalesOrderItem(boolean)</a>.
     **/
    public SalesOrderItem() {
        this(true);
    }

    public SalesOrderItem(final boolean withDefaults) {
        super(withDefaults, com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.salesOrderItem);
    }

    public @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.example.sapinitialproject.ESPM.SalesOrderItem copy() {
        return com.example.sapinitialproject.ESPM.internal.Any_as_com_example_sapinitialproject_ESPM_SalesOrderItem.cast(this.copyEntity());
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String getCurrencyCode() {
        return com.sap.cloud.mobile.odata.StringValue.toNullable(this.getOptionalValue(com.example.sapinitialproject.ESPM.SalesOrderItem.currencyCode));
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable com.sap.cloud.mobile.odata.LocalDateTime getDeliveryDate() {
        return com.sap.cloud.mobile.odata.LocalDateTime.castOptional(this.getOptionalValue(com.example.sapinitialproject.ESPM.SalesOrderItem.deliveryDate));
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable java.math.BigDecimal getGrossAmount() {
        return com.sap.cloud.mobile.odata.DecimalValue.toNullable(this.getOptionalValue(com.example.sapinitialproject.ESPM.SalesOrderItem.grossAmount));
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable com.example.sapinitialproject.ESPM.SalesOrderHeader getHeader() {
        return com.example.sapinitialproject.ESPM.internal.Any_asNullable_com_example_sapinitialproject_ESPM_SalesOrderHeader.cast(this.getOptionalValue(com.example.sapinitialproject.ESPM.SalesOrderItem.header));
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable Integer getItemNumber() {
        return com.sap.cloud.mobile.odata.IntValue.toNullable(this.getOptionalValue(com.example.sapinitialproject.ESPM.SalesOrderItem.itemNumber));
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable java.math.BigDecimal getNetAmount() {
        return com.sap.cloud.mobile.odata.DecimalValue.toNullable(this.getOptionalValue(com.example.sapinitialproject.ESPM.SalesOrderItem.netAmount));
    }

    public @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.example.sapinitialproject.ESPM.SalesOrderItem getOld() {
        return com.example.sapinitialproject.ESPM.internal.Any_as_com_example_sapinitialproject_ESPM_SalesOrderItem.cast(this.getOldEntity());
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable com.example.sapinitialproject.ESPM.Product getProductDetails() {
        return com.example.sapinitialproject.ESPM.internal.Any_asNullable_com_example_sapinitialproject_ESPM_Product.cast(this.getOptionalValue(com.example.sapinitialproject.ESPM.SalesOrderItem.productDetails));
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String getProductID() {
        return com.sap.cloud.mobile.odata.StringValue.toNullable(this.getOptionalValue(com.example.sapinitialproject.ESPM.SalesOrderItem.productID));
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable java.math.BigDecimal getQuantity() {
        return com.sap.cloud.mobile.odata.DecimalValue.toNullable(this.getOptionalValue(com.example.sapinitialproject.ESPM.SalesOrderItem.quantity));
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String getQuantityUnit() {
        return com.sap.cloud.mobile.odata.StringValue.toNullable(this.getOptionalValue(com.example.sapinitialproject.ESPM.SalesOrderItem.quantityUnit));
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String getSalesOrderID() {
        return com.sap.cloud.mobile.odata.StringValue.toNullable(this.getOptionalValue(com.example.sapinitialproject.ESPM.SalesOrderItem.salesOrderID));
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable java.math.BigDecimal getTaxAmount() {
        return com.sap.cloud.mobile.odata.DecimalValue.toNullable(this.getOptionalValue(com.example.sapinitialproject.ESPM.SalesOrderItem.taxAmount));
    }

    /**
     ** {@inheritDoc}
     **/
    @java.lang.Override public boolean isProxy() {
        return true;
    }

    public static @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.EntityKey key(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable Integer itemNumber, final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String salesOrderID) {
        return new com.sap.cloud.mobile.odata.EntityKey().with("ItemNumber", com.sap.cloud.mobile.odata.IntValue.ofNullable(itemNumber)).with("SalesOrderId", com.sap.cloud.mobile.odata.StringValue.ofNullable(salesOrderID));
    }

    public static @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull java.util.List<com.example.sapinitialproject.ESPM.@org.jetbrains.annotations.NotNull SalesOrderItem> list(final @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.EntityValueList from) {
        return com.sap.cloud.mobile.odata.core.ListConverter.<com.sap.cloud.mobile.odata.EntityValue,com.example.sapinitialproject.ESPM.SalesOrderItem>convert(from.toGeneric());
    }

    public void setCurrencyCode(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String value) {
        this.setOptionalValue(com.example.sapinitialproject.ESPM.SalesOrderItem.currencyCode, com.sap.cloud.mobile.odata.StringValue.ofNullable(value));
    }

    public void setDeliveryDate(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable com.sap.cloud.mobile.odata.LocalDateTime value) {
        this.setOptionalValue(com.example.sapinitialproject.ESPM.SalesOrderItem.deliveryDate, value);
    }

    public void setGrossAmount(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable java.math.BigDecimal value) {
        this.setOptionalValue(com.example.sapinitialproject.ESPM.SalesOrderItem.grossAmount, com.sap.cloud.mobile.odata.DecimalValue.ofNullable(value));
    }

    public void setHeader(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable com.example.sapinitialproject.ESPM.SalesOrderHeader value) {
        this.setOptionalValue(com.example.sapinitialproject.ESPM.SalesOrderItem.header, value);
    }

    public void setItemNumber(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable Integer value) {
        this.setOptionalValue(com.example.sapinitialproject.ESPM.SalesOrderItem.itemNumber, com.sap.cloud.mobile.odata.IntValue.ofNullable(value));
    }

    public void setNetAmount(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable java.math.BigDecimal value) {
        this.setOptionalValue(com.example.sapinitialproject.ESPM.SalesOrderItem.netAmount, com.sap.cloud.mobile.odata.DecimalValue.ofNullable(value));
    }

    public void setProductDetails(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable com.example.sapinitialproject.ESPM.Product value) {
        this.setOptionalValue(com.example.sapinitialproject.ESPM.SalesOrderItem.productDetails, value);
    }

    public void setProductID(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String value) {
        this.setOptionalValue(com.example.sapinitialproject.ESPM.SalesOrderItem.productID, com.sap.cloud.mobile.odata.StringValue.ofNullable(value));
    }

    public void setQuantity(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable java.math.BigDecimal value) {
        this.setOptionalValue(com.example.sapinitialproject.ESPM.SalesOrderItem.quantity, com.sap.cloud.mobile.odata.DecimalValue.ofNullable(value));
    }

    public void setQuantityUnit(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String value) {
        this.setOptionalValue(com.example.sapinitialproject.ESPM.SalesOrderItem.quantityUnit, com.sap.cloud.mobile.odata.StringValue.ofNullable(value));
    }

    public void setSalesOrderID(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String value) {
        this.setOptionalValue(com.example.sapinitialproject.ESPM.SalesOrderItem.salesOrderID, com.sap.cloud.mobile.odata.StringValue.ofNullable(value));
    }

    public void setTaxAmount(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable java.math.BigDecimal value) {
        this.setOptionalValue(com.example.sapinitialproject.ESPM.SalesOrderItem.taxAmount, com.sap.cloud.mobile.odata.DecimalValue.ofNullable(value));
    }
}
