//# Do not modify this file -- YOUR CHANGES WILL BE ERASED!
//  Generated by SAP Cloud Platform Android SDK 2.0.0, on Fri Mar 15 17:00:06 BRT 2019
//  Proxy Generator Version: 18.11.0-9ee469-20181119

package com.example.sapinitialproject.ESPM;

public class SalesOrderHeader extends com.sap.cloud.mobile.odata.EntityValue implements android.os.Parcelable {
    public static final android.os.Parcelable.Creator<SalesOrderHeader> CREATOR = new android.os.Parcelable.Creator<SalesOrderHeader>() {
        public SalesOrderHeader createFromParcel(android.os.Parcel in) {
            com.sap.cloud.mobile.odata.JsonEntityProvider provider = com.sap.cloud.mobile.odata.JsonEntityProvider.withMetadata(ESPMContainerMetadata.document);
            ESPMContainer service = new ESPMContainer(provider);
            com.sap.cloud.mobile.odata.DataQuery query = com.sap.cloud.mobile.odata.FromJSON.entity(in.readString());
            query.setEntitySet(ESPMContainerMetadata.EntitySets.salesOrderHeaders);
            query.setEntityType(ESPMContainerMetadata.EntityTypes.salesOrderHeader);
            com.sap.cloud.mobile.odata.EntityValue entity = service.executeQuery(query).getRequiredEntity();
            return (SalesOrderHeader)entity;
        }

        public SalesOrderHeader[] newArray(int size) {
            return new SalesOrderHeader[size];
        }
    };

    public int describeContents() {
        return 0;
    }

    public void writeToParcel(android.os.Parcel out, int flags) {
        out.writeString(com.sap.cloud.mobile.odata.ToJSON.entity(this, com.sap.cloud.mobile.odata.DataContext.FULL_METADATA));
    }

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property createdAt = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.salesOrderHeader.getProperty("CreatedAt");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property currencyCode = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.salesOrderHeader.getProperty("CurrencyCode");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property customerID = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.salesOrderHeader.getProperty("CustomerId");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property grossAmount = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.salesOrderHeader.getProperty("GrossAmount");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property lifeCycleStatus = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.salesOrderHeader.getProperty("LifeCycleStatus");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property lifeCycleStatusName = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.salesOrderHeader.getProperty("LifeCycleStatusName");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property netAmount = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.salesOrderHeader.getProperty("NetAmount");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property salesOrderID = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.salesOrderHeader.getProperty("SalesOrderId");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property taxAmount = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.salesOrderHeader.getProperty("TaxAmount");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property items = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.salesOrderHeader.getProperty("Items");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property customerDetails = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.salesOrderHeader.getProperty("CustomerDetails");

    /**
     ** See <a href='#SalesOrderHeader-boolean-'>SalesOrderHeader(boolean)</a>.
     **/
    public SalesOrderHeader() {
        this(true);
    }

    public SalesOrderHeader(final boolean withDefaults) {
        super(withDefaults, com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.salesOrderHeader);
    }

    public @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.example.sapinitialproject.ESPM.SalesOrderHeader copy() {
        return com.example.sapinitialproject.ESPM.internal.Any_as_com_example_sapinitialproject_ESPM_SalesOrderHeader.cast(this.copyEntity());
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable com.sap.cloud.mobile.odata.LocalDateTime getCreatedAt() {
        return com.sap.cloud.mobile.odata.LocalDateTime.castOptional(this.getOptionalValue(com.example.sapinitialproject.ESPM.SalesOrderHeader.createdAt));
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String getCurrencyCode() {
        return com.sap.cloud.mobile.odata.StringValue.toNullable(this.getOptionalValue(com.example.sapinitialproject.ESPM.SalesOrderHeader.currencyCode));
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable com.example.sapinitialproject.ESPM.Customer getCustomerDetails() {
        return com.example.sapinitialproject.ESPM.internal.Any_asNullable_com_example_sapinitialproject_ESPM_Customer.cast(this.getOptionalValue(com.example.sapinitialproject.ESPM.SalesOrderHeader.customerDetails));
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String getCustomerID() {
        return com.sap.cloud.mobile.odata.StringValue.toNullable(this.getOptionalValue(com.example.sapinitialproject.ESPM.SalesOrderHeader.customerID));
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable java.math.BigDecimal getGrossAmount() {
        return com.sap.cloud.mobile.odata.DecimalValue.toNullable(this.getOptionalValue(com.example.sapinitialproject.ESPM.SalesOrderHeader.grossAmount));
    }

    public @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull java.util.List<com.example.sapinitialproject.ESPM.@org.jetbrains.annotations.NotNull SalesOrderItem> getItems() {
        return com.sap.cloud.mobile.odata.core.ListConverter.<com.sap.cloud.mobile.odata.EntityValue,com.example.sapinitialproject.ESPM.SalesOrderItem>convert(com.sap.cloud.mobile.odata.EntityValueList.castRequired(this.getRequiredValue(com.example.sapinitialproject.ESPM.SalesOrderHeader.items)).toGeneric());
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String getLifeCycleStatus() {
        return com.sap.cloud.mobile.odata.StringValue.toNullable(this.getOptionalValue(com.example.sapinitialproject.ESPM.SalesOrderHeader.lifeCycleStatus));
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String getLifeCycleStatusName() {
        return com.sap.cloud.mobile.odata.StringValue.toNullable(this.getOptionalValue(com.example.sapinitialproject.ESPM.SalesOrderHeader.lifeCycleStatusName));
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable java.math.BigDecimal getNetAmount() {
        return com.sap.cloud.mobile.odata.DecimalValue.toNullable(this.getOptionalValue(com.example.sapinitialproject.ESPM.SalesOrderHeader.netAmount));
    }

    public @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.example.sapinitialproject.ESPM.SalesOrderHeader getOld() {
        return com.example.sapinitialproject.ESPM.internal.Any_as_com_example_sapinitialproject_ESPM_SalesOrderHeader.cast(this.getOldEntity());
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String getSalesOrderID() {
        return com.sap.cloud.mobile.odata.StringValue.toNullable(this.getOptionalValue(com.example.sapinitialproject.ESPM.SalesOrderHeader.salesOrderID));
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable java.math.BigDecimal getTaxAmount() {
        return com.sap.cloud.mobile.odata.DecimalValue.toNullable(this.getOptionalValue(com.example.sapinitialproject.ESPM.SalesOrderHeader.taxAmount));
    }

    /**
     ** {@inheritDoc}
     **/
    @java.lang.Override public boolean isProxy() {
        return true;
    }

    public static @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.EntityKey key(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String salesOrderID) {
        return new com.sap.cloud.mobile.odata.EntityKey().with("SalesOrderId", com.sap.cloud.mobile.odata.StringValue.ofNullable(salesOrderID));
    }

    public static @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull java.util.List<com.example.sapinitialproject.ESPM.@org.jetbrains.annotations.NotNull SalesOrderHeader> list(final @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.EntityValueList from) {
        return com.sap.cloud.mobile.odata.core.ListConverter.<com.sap.cloud.mobile.odata.EntityValue,com.example.sapinitialproject.ESPM.SalesOrderHeader>convert(from.toGeneric());
    }

    public void setCreatedAt(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable com.sap.cloud.mobile.odata.LocalDateTime value) {
        this.setOptionalValue(com.example.sapinitialproject.ESPM.SalesOrderHeader.createdAt, value);
    }

    public void setCurrencyCode(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String value) {
        this.setOptionalValue(com.example.sapinitialproject.ESPM.SalesOrderHeader.currencyCode, com.sap.cloud.mobile.odata.StringValue.ofNullable(value));
    }

    public void setCustomerDetails(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable com.example.sapinitialproject.ESPM.Customer value) {
        this.setOptionalValue(com.example.sapinitialproject.ESPM.SalesOrderHeader.customerDetails, value);
    }

    public void setCustomerID(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String value) {
        this.setOptionalValue(com.example.sapinitialproject.ESPM.SalesOrderHeader.customerID, com.sap.cloud.mobile.odata.StringValue.ofNullable(value));
    }

    public void setGrossAmount(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable java.math.BigDecimal value) {
        this.setOptionalValue(com.example.sapinitialproject.ESPM.SalesOrderHeader.grossAmount, com.sap.cloud.mobile.odata.DecimalValue.ofNullable(value));
    }

    public void setItems(final @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull java.util.List<com.example.sapinitialproject.ESPM.@org.jetbrains.annotations.NotNull SalesOrderItem> value) {
        com.example.sapinitialproject.ESPM.SalesOrderHeader.items.setEntityList(this, com.sap.cloud.mobile.odata.EntityValueList.from(com.sap.cloud.mobile.odata.core.ListConverter.<com.example.sapinitialproject.ESPM.SalesOrderItem,com.sap.cloud.mobile.odata.EntityValue>convert(value)));
    }

    public void setLifeCycleStatus(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String value) {
        this.setOptionalValue(com.example.sapinitialproject.ESPM.SalesOrderHeader.lifeCycleStatus, com.sap.cloud.mobile.odata.StringValue.ofNullable(value));
    }

    public void setLifeCycleStatusName(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String value) {
        this.setOptionalValue(com.example.sapinitialproject.ESPM.SalesOrderHeader.lifeCycleStatusName, com.sap.cloud.mobile.odata.StringValue.ofNullable(value));
    }

    public void setNetAmount(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable java.math.BigDecimal value) {
        this.setOptionalValue(com.example.sapinitialproject.ESPM.SalesOrderHeader.netAmount, com.sap.cloud.mobile.odata.DecimalValue.ofNullable(value));
    }

    public void setSalesOrderID(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String value) {
        this.setOptionalValue(com.example.sapinitialproject.ESPM.SalesOrderHeader.salesOrderID, com.sap.cloud.mobile.odata.StringValue.ofNullable(value));
    }

    public void setTaxAmount(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable java.math.BigDecimal value) {
        this.setOptionalValue(com.example.sapinitialproject.ESPM.SalesOrderHeader.taxAmount, com.sap.cloud.mobile.odata.DecimalValue.ofNullable(value));
    }
}
