//# Do not modify this file -- YOUR CHANGES WILL BE ERASED!
//  Generated by SAP Cloud Platform Android SDK 2.0.0, on Fri Mar 15 17:00:06 BRT 2019
//  Proxy Generator Version: 18.11.0-9ee469-20181119

package com.example.sapinitialproject.ESPM;

public class Supplier extends com.sap.cloud.mobile.odata.EntityValue implements android.os.Parcelable {
    public static final android.os.Parcelable.Creator<Supplier> CREATOR = new android.os.Parcelable.Creator<Supplier>() {
        public Supplier createFromParcel(android.os.Parcel in) {
            com.sap.cloud.mobile.odata.JsonEntityProvider provider = com.sap.cloud.mobile.odata.JsonEntityProvider.withMetadata(ESPMContainerMetadata.document);
            ESPMContainer service = new ESPMContainer(provider);
            com.sap.cloud.mobile.odata.DataQuery query = com.sap.cloud.mobile.odata.FromJSON.entity(in.readString());
            query.setEntitySet(ESPMContainerMetadata.EntitySets.suppliers);
            query.setEntityType(ESPMContainerMetadata.EntityTypes.supplier);
            com.sap.cloud.mobile.odata.EntityValue entity = service.executeQuery(query).getRequiredEntity();
            return (Supplier)entity;
        }

        public Supplier[] newArray(int size) {
            return new Supplier[size];
        }
    };

    public int describeContents() {
        return 0;
    }

    public void writeToParcel(android.os.Parcel out, int flags) {
        out.writeString(com.sap.cloud.mobile.odata.ToJSON.entity(this, com.sap.cloud.mobile.odata.DataContext.FULL_METADATA));
    }

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property city = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.supplier.getProperty("City");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property country = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.supplier.getProperty("Country");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property emailAddress = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.supplier.getProperty("EmailAddress");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property houseNumber = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.supplier.getProperty("HouseNumber");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property phoneNumber = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.supplier.getProperty("PhoneNumber");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property postalCode = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.supplier.getProperty("PostalCode");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property street = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.supplier.getProperty("Street");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property supplierID = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.supplier.getProperty("SupplierId");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property supplierName = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.supplier.getProperty("SupplierName");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property address = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.supplier.getProperty("Address");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property updatedTimestamp = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.supplier.getProperty("UpdatedTimestamp");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property products = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.supplier.getProperty("Products");

    public static volatile @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.Property purchaseOrders = com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.supplier.getProperty("PurchaseOrders");

    /**
     ** See <a href='#Supplier-boolean-'>Supplier(boolean)</a>.
     **/
    public Supplier() {
        this(true);
    }

    public Supplier(final boolean withDefaults) {
        super(withDefaults, com.example.sapinitialproject.ESPM.ESPMContainerMetadata.EntityTypes.supplier);
    }

    public @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.example.sapinitialproject.ESPM.Supplier copy() {
        return com.example.sapinitialproject.ESPM.internal.Any_as_com_example_sapinitialproject_ESPM_Supplier.cast(this.copyEntity());
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable com.example.sapinitialproject.ESPM.Address getAddress() {
        return com.example.sapinitialproject.ESPM.internal.Any_asNullable_com_example_sapinitialproject_ESPM_Address.cast(this.getOptionalValue(com.example.sapinitialproject.ESPM.Supplier.address));
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String getCity() {
        return com.sap.cloud.mobile.odata.StringValue.toNullable(this.getOptionalValue(com.example.sapinitialproject.ESPM.Supplier.city));
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String getCountry() {
        return com.sap.cloud.mobile.odata.StringValue.toNullable(this.getOptionalValue(com.example.sapinitialproject.ESPM.Supplier.country));
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String getEmailAddress() {
        return com.sap.cloud.mobile.odata.StringValue.toNullable(this.getOptionalValue(com.example.sapinitialproject.ESPM.Supplier.emailAddress));
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String getHouseNumber() {
        return com.sap.cloud.mobile.odata.StringValue.toNullable(this.getOptionalValue(com.example.sapinitialproject.ESPM.Supplier.houseNumber));
    }

    public @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.example.sapinitialproject.ESPM.Supplier getOld() {
        return com.example.sapinitialproject.ESPM.internal.Any_as_com_example_sapinitialproject_ESPM_Supplier.cast(this.getOldEntity());
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String getPhoneNumber() {
        return com.sap.cloud.mobile.odata.StringValue.toNullable(this.getOptionalValue(com.example.sapinitialproject.ESPM.Supplier.phoneNumber));
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String getPostalCode() {
        return com.sap.cloud.mobile.odata.StringValue.toNullable(this.getOptionalValue(com.example.sapinitialproject.ESPM.Supplier.postalCode));
    }

    public @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull java.util.List<com.example.sapinitialproject.ESPM.@org.jetbrains.annotations.NotNull Product> getProducts() {
        return com.sap.cloud.mobile.odata.core.ListConverter.<com.sap.cloud.mobile.odata.EntityValue,com.example.sapinitialproject.ESPM.Product>convert(com.sap.cloud.mobile.odata.EntityValueList.castRequired(this.getRequiredValue(com.example.sapinitialproject.ESPM.Supplier.products)).toGeneric());
    }

    public @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull java.util.List<com.example.sapinitialproject.ESPM.@org.jetbrains.annotations.NotNull PurchaseOrderHeader> getPurchaseOrders() {
        return com.sap.cloud.mobile.odata.core.ListConverter.<com.sap.cloud.mobile.odata.EntityValue,com.example.sapinitialproject.ESPM.PurchaseOrderHeader>convert(com.sap.cloud.mobile.odata.EntityValueList.castRequired(this.getRequiredValue(com.example.sapinitialproject.ESPM.Supplier.purchaseOrders)).toGeneric());
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String getStreet() {
        return com.sap.cloud.mobile.odata.StringValue.toNullable(this.getOptionalValue(com.example.sapinitialproject.ESPM.Supplier.street));
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String getSupplierID() {
        return com.sap.cloud.mobile.odata.StringValue.toNullable(this.getOptionalValue(com.example.sapinitialproject.ESPM.Supplier.supplierID));
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String getSupplierName() {
        return com.sap.cloud.mobile.odata.StringValue.toNullable(this.getOptionalValue(com.example.sapinitialproject.ESPM.Supplier.supplierName));
    }

    public @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable com.sap.cloud.mobile.odata.LocalDateTime getUpdatedTimestamp() {
        return com.sap.cloud.mobile.odata.LocalDateTime.castOptional(this.getOptionalValue(com.example.sapinitialproject.ESPM.Supplier.updatedTimestamp));
    }

    /**
     ** {@inheritDoc}
     **/
    @java.lang.Override public boolean isProxy() {
        return true;
    }

    public static @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.EntityKey key(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String supplierID) {
        return new com.sap.cloud.mobile.odata.EntityKey().with("SupplierId", com.sap.cloud.mobile.odata.StringValue.ofNullable(supplierID));
    }

    public static @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull java.util.List<com.example.sapinitialproject.ESPM.@org.jetbrains.annotations.NotNull Supplier> list(final @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull com.sap.cloud.mobile.odata.EntityValueList from) {
        return com.sap.cloud.mobile.odata.core.ListConverter.<com.sap.cloud.mobile.odata.EntityValue,com.example.sapinitialproject.ESPM.Supplier>convert(from.toGeneric());
    }

    public void setAddress(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable com.example.sapinitialproject.ESPM.Address value) {
        this.setOptionalValue(com.example.sapinitialproject.ESPM.Supplier.address, value);
    }

    public void setCity(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String value) {
        this.setOptionalValue(com.example.sapinitialproject.ESPM.Supplier.city, com.sap.cloud.mobile.odata.StringValue.ofNullable(value));
    }

    public void setCountry(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String value) {
        this.setOptionalValue(com.example.sapinitialproject.ESPM.Supplier.country, com.sap.cloud.mobile.odata.StringValue.ofNullable(value));
    }

    public void setEmailAddress(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String value) {
        this.setOptionalValue(com.example.sapinitialproject.ESPM.Supplier.emailAddress, com.sap.cloud.mobile.odata.StringValue.ofNullable(value));
    }

    public void setHouseNumber(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String value) {
        this.setOptionalValue(com.example.sapinitialproject.ESPM.Supplier.houseNumber, com.sap.cloud.mobile.odata.StringValue.ofNullable(value));
    }

    public void setPhoneNumber(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String value) {
        this.setOptionalValue(com.example.sapinitialproject.ESPM.Supplier.phoneNumber, com.sap.cloud.mobile.odata.StringValue.ofNullable(value));
    }

    public void setPostalCode(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String value) {
        this.setOptionalValue(com.example.sapinitialproject.ESPM.Supplier.postalCode, com.sap.cloud.mobile.odata.StringValue.ofNullable(value));
    }

    public void setProducts(final @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull java.util.List<com.example.sapinitialproject.ESPM.@org.jetbrains.annotations.NotNull Product> value) {
        com.example.sapinitialproject.ESPM.Supplier.products.setEntityList(this, com.sap.cloud.mobile.odata.EntityValueList.from(com.sap.cloud.mobile.odata.core.ListConverter.<com.example.sapinitialproject.ESPM.Product,com.sap.cloud.mobile.odata.EntityValue>convert(value)));
    }

    public void setPurchaseOrders(final @android.support.annotation.NonNull @org.jetbrains.annotations.NotNull java.util.List<com.example.sapinitialproject.ESPM.@org.jetbrains.annotations.NotNull PurchaseOrderHeader> value) {
        com.example.sapinitialproject.ESPM.Supplier.purchaseOrders.setEntityList(this, com.sap.cloud.mobile.odata.EntityValueList.from(com.sap.cloud.mobile.odata.core.ListConverter.<com.example.sapinitialproject.ESPM.PurchaseOrderHeader,com.sap.cloud.mobile.odata.EntityValue>convert(value)));
    }

    public void setStreet(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String value) {
        this.setOptionalValue(com.example.sapinitialproject.ESPM.Supplier.street, com.sap.cloud.mobile.odata.StringValue.ofNullable(value));
    }

    public void setSupplierID(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String value) {
        this.setOptionalValue(com.example.sapinitialproject.ESPM.Supplier.supplierID, com.sap.cloud.mobile.odata.StringValue.ofNullable(value));
    }

    public void setSupplierName(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable String value) {
        this.setOptionalValue(com.example.sapinitialproject.ESPM.Supplier.supplierName, com.sap.cloud.mobile.odata.StringValue.ofNullable(value));
    }

    public void setUpdatedTimestamp(final @android.support.annotation.Nullable @org.jetbrains.annotations.Nullable com.sap.cloud.mobile.odata.LocalDateTime value) {
        this.setOptionalValue(com.example.sapinitialproject.ESPM.Supplier.updatedTimestamp, value);
    }
}
